#ifndef DEFINICOES_H
#define DEFINICOES_H

#define PI 3.14159265358979323846

#define RAIO_JANTE    0.06f
#define LARGURA_JANTE 0.17f
#define ALTURA_PNEU   0.3f
#define LARGURA_PNEU  0.3f
#define RAIO_RODA (ALTURA_PNEU + RAIO_JANTE)
#define DIAMETRO_RODA (RAIO_RODA * 2.0f)

#define BRECAGEM_MAXIMA 45.0f

//EIXOS
#define RAIO_EIXO 0.035f

#define ALTURA_VEICULO  1.4f
#define LARGURA_VEICULO 2.0f
#define COMPRIMENTO_VEICULO 3.2f
#define DISTANCIA_CAVA_DA_RODA_A_FRENTE 0.3
#define DISTANCIA_CAVA_DA_RODA_A_TRAS 0.15

#endif